# Generated by Django 5.0.7 on 2025-07-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('task', models.CharField(max_length=100)),
                ('end', models.IntegerField()),
            ],
        ),
    ]
