# Generated by Django 5.0.7 on 2025-07-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start',
            field=models.DateField(),
        ),
    ]
